#
# Use nix-emacs-ci for travis CI
# URL: https://github.com/purcell/nix-emacs-ci
#

language: nix

os:
  - linux
  - osx

env:
  - EMACS_CI=emacs-24-2
  - EMACS_CI=emacs-24-3
  - EMACS_CI=emacs-24-2
  - EMACS_CI=emacs-24-3
  - EMACS_CI=emacs-24-4
  - EMACS_CI=emacs-24-5
  - EMACS_CI=emacs-25-1
  - EMACS_CI=emacs-25-2
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot

# The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - export PATH="$HOME/.cask/bin:$PATH"
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

script:
  - emacs --version
  - make clean
  - make
  - make test

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
